# Torchquad - example notebook

Torchquad is a powerful tool for numerical integration in multiple dimensions. It was developed by scientists in the Advanced Concepts Team at the European Space Agency. 

The name is an amalgam of *torch* (from  [PyTorch][1]) and *quad* (from the term *numerical quadrature*). According to [Wikipedia][2], some authors refer to numerical integration over more than one dimension as *cubature*; others take *quadrature* to include higher-dimensional integration as well. As you might have guessed, the authors of this package belong to the latter group:  
**torchquad does multidimensional numerical integration using the PyTorch framework**.

[1]: https://pytorch.org/
[2]: https://en.wikipedia.org/wiki/Numerical_integration

So why wouldn't you just use other integration tools, like [scipy.integrate.quad][3] or [.nquad][4]? Over *n* dimensions, the computation simply becomes too costly if *n* is large&#151;this problem is known as the *curse of dimensionality*. A solution is to take a shortcut, i.e. by evaluating the integrand at equally or randomly spaced points. The curse of dimensionality still applies, but at much larger *n*.

The different integration methods in the torchquad package include [Monte Carlo integration][5], a technique for numerical integration using random numbers, and the [Newton-Cotes formulas][6], of which the Trapezoid rule and Simpson's rule are of the most famous members.

[3]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad
[4]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.nquad.html#scipy.integrate.nquad
[5]: https://en.wikipedia.org/wiki/Monte_Carlo_integration
[6]: https://en.wikipedia.org/wiki/Newton%E2%80%93Cotes_formulas

| Common name        | How it works                                                      | Spacing |
|--------------------|-------------------------------------------------------------------|---------|
| Trapezoid rule     | Creates a linear interpolant between two neighbouring points      | Equal   |
| Simpson's rule     | Creates a quadratic interpolant between three neighbouring points | Equal   |
| Monte Carlo method | Randomly chooses points at which the integrand is evaluated       | Random  |

`Could insert a table in markdown showing the different methods the user can use?`  
See: <https://www.tablesgenerator.com/markdown_tables>  
From: <https://en.wikipedia.org/wiki/Newton%E2%80%93Cotes_formulas#Closed_Newton%E2%80%93Cotes_formulas>  

We believe that this new architecture will soon be in the toolbox of any data scientist&#151;from those working on asteroid mass estimation to those who ... 

### Outline 
This notebook is a guide for new users to torchquad and is structured in the following way:

* Example integration in one dimension (1-D)  
* Example integration in three dimensions (3-D)  
* How to do integration in *n* dimensions (*n*-D)  
* Convergence plots  
* Run-time comparison with `scipy.integrate.nquad`

## Imports
Now let's get started! First, the general imports:

In [1]:
import numpy as np
import scipy

#For plotting
import matplotlib.pyplot as plt

import torch

use_cuda = torch.cuda.is_available()

Oh, and you have to decide if you want to enable the GPU. Run the cell below to enable CUDA.

In [3]:
# I have no idea what I'm doing here.

## One dimensional integration

To make sure everyone is following the methods used in this notebook, we will start in one dimension. See [Patrick Walls][1]' nice Python introduction to the [Trapezoid rule][2] and [Simpson's rule][3] in one dimension. 

`f1` is the function $ f(x) = x^2 + 1 $, and `f2` is $ f(x) = \sin{x} $.  
Over the domain $[-2,2]$, `f1` should give the result $\int_{-2}^{2} (x^2 + 1) \,dx = \frac{28}{3} = 9.33333333333333 $.  
Over the domain $[-10,1]$, `f2` should give the result $\int_{-10}^{1} \sin{x} \,dx = -1.37937383494459 $.

[1]: https://github.com/patrickwalls
[2]: https://www.math.ubc.ca/~pwalls/math-python/integration/trapezoid-rule/
[3]: https://www.math.ubc.ca/~pwalls/math-python/integration/simpsons-rule/

In [14]:
from torchquad import MonteCarlo, Trapezoid1D

def f1(x):
    return x**2 + 1

integration_domain = [[-2, 2]]
tp = Trapezoid1D()
for N in [4,16,100, 1000, 66666]:
    a = tp.integrate(f1, N, integration_domain)
    print(a)

tensor([10.5185])
tensor([9.3807])
tensor([9.3344])
tensor([9.3333])
tensor([9.3272])
